#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /register
  controller: App\Controller\UserAuthenticator::register
  methods: POST

api:
  path: /api
  controller: App\Controller\UserAuthenticator::api

login_check:
  path: /login_check
  methods: [POST]
